name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "langgithub@gmail.com"
          git config --local user.name "langgithub"
          git remote set-url origin git@github.com:langgithub/auto-green.git
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
